# Generated by Django 4.2.11 on 2025-06-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_remove_facture_produits_lignefacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='produits',
            field=models.ManyToManyField(to='produits.produit'),
        ),
    ]
