# Generated by Django 4.2.11 on 2025-06-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_facture_produits'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='clients',
            field=models.CharField(default='Client', max_length=100),
        ),
    ]
