# Generated by Django 4.2.11 on 2025-06-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_facture_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='clients',
            new_name='client',
        ),
    ]
